import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  weight: ["100", "200", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${inter.className} h-full flex flex-col bg-background`}>
        <Header />
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
